// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the authenticated user's ID and email. Useful to verify the MCP connection is working.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-jobs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anon, {
    global: {
      headers: { Authorization: `Bearer ${ctx.getToken()}` }
    },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function getCurrentOrganizationId(sb, userId) {
  const { data, error } = await sb.from("organization_members").select("organization_id").eq("user_id", userId).limit(1).maybeSingle();
  if (error || !data) return null;
  return data.organization_id;
}

// src/lib/mcp/tools/list-jobs.ts
var list_jobs_default = defineTool2({
  name: "list_jobs",
  title: "List jobs",
  description: "List the current user's organization jobs (vagas). Returns id, title, status and creation date. Respects the user's access via RLS.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. 'open', 'closed'."),
    limit: z.number().int().optional().describe("Maximum rows to return (default 20, max 100).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const orgId = await getCurrentOrganizationId(sb, ctx.getUserId());
    if (!orgId) {
      return {
        content: [{ type: "text", text: "No organization found for this user." }],
        isError: true
      };
    }
    const cap = Math.min(Math.max(limit ?? 20, 1), 100);
    let q = sb.from("jobs").select("id, title, status, created_at").eq("organization_id", orgId).order("created_at", { ascending: false }).limit(cap);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-candidates.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_candidates_default = defineTool3({
  name: "list_candidates",
  title: "List candidates for a job",
  description: "List candidates (job applications) for a given job ID. Returns candidate name, email, current stage and application date.",
  inputSchema: {
    job_id: z2.string().uuid().describe("The job (vaga) UUID to list candidates for."),
    limit: z2.number().int().optional().describe("Max rows (default 50, max 200).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ job_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const cap = Math.min(Math.max(limit ?? 50, 1), 200);
    const { data, error } = await sb.from("job_applications").select("id, candidate_name, candidate_email, stage_id, created_at, status").eq("job_id", job_id).order("created_at", { ascending: false }).limit(cap);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { candidates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-employees.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_employees_default = defineTool4({
  name: "list_employees",
  title: "List employees",
  description: "List employees of the current user's organization. Optionally filter by name (case-insensitive substring).",
  inputSchema: {
    search: z3.string().optional().describe("Optional name substring to filter by."),
    limit: z3.number().int().optional().describe("Max rows (default 50, max 200).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const orgId = await getCurrentOrganizationId(sb, ctx.getUserId());
    if (!orgId) {
      return {
        content: [{ type: "text", text: "No organization found for this user." }],
        isError: true
      };
    }
    const cap = Math.min(Math.max(limit ?? 50, 1), 200);
    let q = sb.from("employees").select("id, full_name, email, status, position_id, department_id, created_at").eq("organization_id", orgId).order("full_name", { ascending: true }).limit(cap);
    if (search) q = q.ilike("full_name", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { employees: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yjrnudslswuivqoqkbqq";
var mcp_default = defineMcp({
  name: "pwr-hr-mcp",
  title: "PWR Gest\xE3o HR",
  version: "0.1.0",
  instructions: "Ferramentas do PWR Gest\xE3o (RH). Cada chamada roda como o usu\xE1rio autenticado e respeita as permiss\xF5es (RLS) da organiza\xE7\xE3o. Use `whoami` para confirmar a conex\xE3o; `list_jobs`, `list_candidates` e `list_employees` para consultar dados da organiza\xE7\xE3o atual do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_jobs_default, list_candidates_default, list_employees_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
